import { Inter } from 'next/font/google'
import './globals.css'
import 'app/styles/home.modules.css'
import Provider from './context/AuthContext'
import ToasterContext from './context/ToasterContext'
import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core"; 
config.autoAddCss = false;
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, Component, pageProps}) {
  return (
      <html className='min-h-screen relative' lang="en">
        <body className={inter.className}>
          <Provider>
            <ToasterContext />
            {children}
            <Footer/>
          </Provider>
        </body>
      </html>
  )
}

